<?php $this->layout('layout::main_template') ?>
<div class="container">
    <div class="jumbotron">
        <h1>Seu e-mail foi cadastrado com sucesso em nosso banco de dados.</h1>

        <p>
            Em breve você receberá novidades.
        </p>

        <p>
            <a class="btn btn-primary btn-lg" href="<?= $this->url(array('home')) ?>" role="button">
                Continuar navegando
            </a>
        </p>
    </div>
</div>
