version: '2'

services:
  webserver:
    build: ./
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    links:
      - database

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:4.6.4-1
      container_name: phpmyadmin
      environment:
       - PMA_ARBITRARY=0
       - PMA_HOST=database
       - PMA_USER=root
      ports:
       - 8080:80
      depends_on:
       - database
      links:
       - database

  database:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: db
