<?php $this->layout('error::erro_template') ?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!</h1>

                <h2>
                    404 Não encontrado</h2>

                <div class="error-details">
                    Desculpe, ocorreu um erro e a página solicitada não foi encontrada.
                </div>
                <div class="error-actions">
                    <a href="<?= $this->url(array('home')) ?>" class="btn btn-primary btn-lg">
                        <span class="glyphicon glyphicon-home"></span>
                        Home
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
