<?php
/** @var $usuario \Egressos\Application\Model\UserModel */
?>
<img src="<?= $usuario->getAvatar() ?>" alt="<?= $usuario->nome ?>">
<h2><?= $usuario->nome ?></h2>
<?php
if ($usuario->receber_feed == 'Sim') {
    ?>
    <h3>Disponível para novas oportunidades e projetos</h3>
    <?php
}
?>
<?php
if ($usuario->trabalhando == 'Sim') {
    ?>
    <h4>Atualmente empregado</h4>
    <?php
} else {
    ?>
    <h4>Atualmente desempregado</h4>
    <?php
}
?>
<h4><?= $usuario->getTitulacao()->nome ?> em <?= $usuario->getCurso()->nome ?></h4>
<h4>Câmpus: <?= $usuario->getCampus()->nome ?></h4>
<h4>Turma: <?= $usuario->ano_entrada ?>-<?= $usuario->ano_conclusao ?></h4>
<h4>Email: <?= $usuario->email ?></h4>
<ul>
    <li><a href="<?= $this->url(['dashboard']) ?>" alt="">Ver meu perfil</a></li>
    <li><a href="<?= $this->url(['editar-perfil']) ?>" alt="">Editar meu perfil</a></li>
    <li><a href="<?= $this->url(['amigos']) ?>" alt="">Ver meus amigos</a></li>
    <li><a href="<?= $this->url(['oportunidades']) ?>" alt="">Oportunidades</a></li>
    <li><a href="<?= $this->url(['logout']) ?>" alt="">Sair</a></li>
</ul>
