<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="index, follow">
    <title><?= isset($title) ? $title : '' ?> <?= isset($endingTitle) ? $endingTitle : ' - Egressos' ?></title>
    <meta name="description"
          content="<?= $metaDescription ? $metaDescription : 'IFSP - Egressos' ?>">

    <link rel="icon" href="<?= $this->getPublicAssetsUrl() ?>/images/favicon.ico">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= $this->getPublicAssetsUrl() ?>/css/bootstrap-tagsinput.css">
    <link rel="stylesheet" href="<?= $this->getPublicAssetsUrl() ?>/css/main.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav class="topo navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="hidden-xs" href="<?= $this->url('home') ?>">
                <img src="<?= $this->getPublicAssetsUrl() ?>/images/logo.png" width="200" alt="">
            </a>
        </div>
    </div>
</nav>

<div class="container">
    <?= $this->section('content') ?>
</div>
<footer class="container text-center">
    <hr/>
    <div class="row">
        <div class="col-md-4">
            <img class="logo-footer" src="<?= $this->getPublicAssetsUrl() ?>/images/logo-footer.png" alt="Sistema de Egressos">
        </div>
        <div class="col-md-8">
            <h3>Localização</h3>
            <address>
                Instituto Federal De Educação, Ciência E Tecnologia De São Paulo - IFSP Campus Campinas Rodovia D. Pedro
                I (SP-65), KM 143,6 - Bairro Amarais Campinas, SP - CEP 13069-901<br>
                Fone: (19) 3746-6128
            </address>
            <a href="mailto:egressos@ifsp.edu.br">egressos@ifsp.edu.br</a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 footer-bottom">
            <p class="text-left">
                IFSP - Todos os direitos reservados
            </p>

        </div>
    </div>
    </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="<?= $this->getPublicAssetsUrl() ?>/js/bootstrap-tagsinput.min.js"></script>
<script src="<?= $this->getPublicAssetsUrl() ?>/js/main.js"></script>
</body>
</html>
