<?php
$this->layout('layout::main_template');
?>

<div class="container">
    <div class="jumbotron">
        <h1>
            Obrigado !
        </h1>

        <p>
            Sua mensagem foi enviada com sucesso.
        </p>

        <p>
            Em breve entraremos em contato.
        </p>

        <p>
            <a class="btn btn-primary btn-lg" href="<?= $this->url(array('home')) ?>" role="button">
                Continuar navegando
            </a>
        </p>
    </div>
</div>
