<?php
$this->layout('layout::main_template', ['title' => 'Seu Perfil']);
?>
<div class=row>
    <div class="col-sm-12">
        <h1>Sistema de Egressos</h1>
    </div>
    <div class="col-md-4 sidebar-user">
        <img src="/public_assets/images/marcacao/teste-foto-perfil.jpg" alt="Nome do egresso">
        <h2>Nome do egresso</h2>
        <h3>Cidade do egresso</h3>
        <h3>Disponível para novas oportunidades e projetos</h3>
        <h4>Trabalha na empresa XXXXXX</h4>
        <ul>
        <li><a href="#" alt="">Ver perfil completo</a></li>
        <li><a href="#" alt="">Ver amigos</a></li>
        <li><a href="#" alt="">Procurar amigos</a></li>
        <li><a href="#" alt="">Oportunidades</a></li>
        </ul>
    </div>
    <div class="col-md-8">
    <img src="/public_assets/images/marcacao/teste-foto-capa.jpg" alt="Nome do egresso">
        <h2>Amigos </h2>
          <div class="row">
        <form action="#" method="post">
            <div class="col-md-8">
                 <div class="form-group">
                        <label for="nome" class="control-label">Digite abaixo o nome de quem procura:</label>
                        <input type="text" class="form-control" name="nome"
                            id="interesse" placeholder="Busque um amigo"/>
                </div>
                <div class="form-group">
                <button type="submit" class="btn btn-lg btn-success">
                    Buscar
                </button>
            </div>
            </div>
        </form>
        </div>
        <p>Resultado da busca:</p>
        <div class="amigos">
            <div class="col-sm-4 col-md-3 col-xs-6">
            <a href="" alt="">
            <div class="image">
            <img src="/public_assets/images/marcacao/teste-amigos.jpg" alt="">
            </div>
            <h3>Nicole Fanys</h3>
            </a>
            <button type="submit" class="btn btn-lg btn-alert">
                Adicionar aos amigos
            </button>
            </div>

        </div>
        

    </div>

</div>
