<?php
$this->layout('layout::main_template', ['title' => 'Amigo adicionado Sucesso']);
?>

<div class="col-md-12">
    <h1>Sistema de Egressos</h1>
    <h2>Solicitação de amizade enviada com sucesso!</h2>
    <p>
        Assim que seu amigo aceitar sua solicitação, uma notificação será enviada para você !
    </p>
    <a href="<?=$this->url(['home'])?>" class="btn btn-default">
        Voltar
    </a>
</div>

