<?php
$this->layout('layout::main_template', ['title' => 'Cadastrar-se']);

if (isset($mensagens)) {
    foreach ($mensagens as $m) {
        if (false == empty($m)) {
            ?>
            <div class="alert alert-danger" role="alert"><?= $m ?></div>
            <?php
        }
    }
}
?>
<h1>
    Sistema de Egressos
</h1>
<h2>
    Cadastro de novos usuários
</h2>
<p>
    Favor preencher os campos abaixo e submeter a solicitação de cadastro.
</p>
<p>
    Assim que as informações forem validadas, enviaremos uma senha de acesso que permitirá a solicitação eletrônica do
    seu pedido.
</p>
<p>
    Se houver alguma dúvida favor entrar em contato pelo telefone 011 3333.3333 ou pelo email: egressos@ifsp.edu.br
</p>

<form action="<?= $this->url(['cadastrar']) ?>" method="post">
    <div class="row">
        <div class="col-md-6">
            <h1>Dados do aluno</h1>
            <div class="form-group">
                <label for="nome" class="control-label">Nome</label>
                <input type="text" class="form-control" name="nome"
                       value="<?= isset($usuario) ? $usuario['nome'] : '' ?>" id="nome"/>
            </div>
            <div class="form-group">
                <label for="email" class="control-label">Email</label>
                <input type="text" class="form-control" name="email"
                       value="<?= isset($usuario) ? $usuario['email'] : '' ?>" id="email"/>
            </div>
            <div class="form-group">
                <label for="password" class="cols-sm-2 control-label">Senha</label>
                <input type="password" class="form-control" name="password" id="password"/>
            </div>
            <div class="form-group">
                <label for="telefone" class="control-label">Telefone</label>
                <input type="text" class="form-control" value="<?= isset($usuario) ? $usuario['telefone'] : '' ?>"
                       name="telefone" id="telefone"/>
            </div>
            <h1>Trabalho</h1>
            <div class="form-group">
                <label for="trabalhando" class="control-label">
                    Esta trabalhando atualmente?
                </label>
            </div>
            <div class="form-group">
                <label class="radio-inline">
                    <input type="radio" <?= isset($usuario['trabalhando']) && $usuario['trabalhando'] == 'Sim' ? 'checked' : '' ?>
                           name="trabalhando" value="Sim"> Sim
                </label>
                <label class="radio-inline">
                    <input type="radio" <?= isset($usuario['trabalhando']) && $usuario['trabalhando'] == 'Não' ? 'checked' : '' ?>
                           name="trabalhando" value="Não"> Não
                </label>
            </div>
            <div class="form-group">
                <label for="trabalhando" class="control-label">
                    Deseja receber propostas e oprotunidades trabalho
                </label>
            </div>
            <div class="form-group">
                <label class="radio-inline">
                    <input type="radio" <?= isset($usuario['receber_feed']) && $usuario['receber_feed'] == 'Sim' ? 'checked' : '' ?>
                           name="receber_feed" value="Sim"> Sim
                </label>
                <label class="radio-inline">
                    <input type="radio" <?= isset($usuario['receber_feed']) && $usuario['receber_feed'] == 'Não' ? 'checked' : '' ?>
                           name="receber_feed" value="Não"> Não
                </label>
            </div>
        </div>
        <div class="col-md-6">
            <h1>Dados do curso</h1>
            <div class="form-group">
                <label for="campus" class="control-label">Câmpus</label>
                <select name="campus" class="form-control" id="campus">
                    <option>Selecione uma opção</option>
                    <?php
                    foreach ($campus as $c) {
                        ?>
                        <option <?= isset($usuario) && $c->id == $usuario['campus'] ? 'selected' : '' ?>
                            value="<?= $c->id ?>"><?= $c->nome ?></option>
                        <?php
                    }
                    ?>
                </select>
            </div>
            <div class="form-group">
                <label for="titulacao" class="control-label">Titulação</label>
                <select name="titulacao" class="form-control" id="titulacao">
                    <option>Selecione uma opção</option>
                    <?php
                    foreach ($titulacoes as $c) {
                        ?>
                        <option <?= isset($usuario) && $c->id == $usuario['titulacao'] ? 'selected' : '' ?>
                            value="<?= $c->id ?>"><?= $c->nome ?></option>
                        <?php
                    }
                    ?>
                </select>
            </div>
            <div class="form-group">
                <label for="curso" class="control-label">Curso</label>
                <select name="curso" class="form-control" id="curso">
                    <option>Selecione uma opção</option>
                    <?php
                    foreach ($cursos as $c) {
                        ?>
                        <option <?= isset($usuario) && $c->id == $usuario['curso'] ? 'selected' : '' ?>
                            value="<?= $c->id ?>"><?= $c->nome ?></option>
                        <?php
                    }
                    ?>
                </select>
            </div>
            <div class="form-group">
                <label for="ano_entrada" class="control-label">Ano de Entrada</label>
                <input type="text" class="form-control" value="<?= isset($usuario) ? $usuario['ano_entrada'] : '' ?>"
                       name="ano_entrada" id="ano_entrada"/>
            </div>
            <div class="form-group">
                <label for="ano_conclusao" class="control-label">Ano de Conclusão</label>
                <input type="text" class="form-control" value="<?= isset($usuario) ? $usuario['ano_conclusao'] : '' ?>"
                       name="ano_conclusao" id="ano_conclusao"/>
            </div>
            <div class="form-group">
                <label for="ra" class="control-label">RA</label>
                <input type="text" class="form-control" value="<?= isset($usuario) ? $usuario['ra'] : '' ?>" name="ra"
                       id="ra"/>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-6">
            <button type="submit" class="btn btn-lg btn-success">
                Concluir o cadastro
            </button>
        </div>
    </div>
</form>
