<?php
$this->layout('layout::main_template', ['title' => 'Cadastro Sucesso']);
?>

<div class="col-md-12">
    <h1>Sistema de Egressos</h1>
    <h2>Cadastro efetuado com sucesso!</h2>
    <p>
        Acesse o link e preencha o formulário para realizar o seu cadastro para acessar informações exclusivas
    </p>
    <a href="<?=$this->url(['login'])?>" class="btn btn-default">
        Visualize seu perfil
    </a>
</div>

