<?php
$this->layout('layout::main_template', ['title' => 'Seu Perfil']);
?>
<form action="#" method="post">
    <div class=row>
        <div class="col-sm-12">
            <h1>Sistema de Egressos</h1>
        </div>
        <div class="col-md-4 sidebar-user">
            <?php $this->insert('partials::sidebar-user', ['usuario' => $usuario]) ?>
        </div>
        <div class="col-md-8">
            <?php $this->insert('partials::banner') ?>
            <h2>Resumo:</h2>
            <p>
                <textarea name="resumo" id="" class="form-control" rows="10"><?= $usuario->resumo ?></textarea>
            </p>
            <h2>Interesses:</h2>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="text" class="form-control tags" name="interesses"
                               id="interesse" value="<?= $usuario->interesses ?>" placeholder="Inserir interesse"/>&nbsp;<label style="font-size:10px"> Utilize a tecla TAB para adicionar novos interesses.</label>
                    </div>
                </div>
                <div class="col-md-6">
                    <button type="submit" class="btn btn-lg btn-success">
                        Salvar
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
