<?php
/**
 * Created by PhpStorm.
 * User: ricardo
 * Date: 08/12/16
 * Time: 11:13
 */
$this->layout('layout::main_template', ['title' => 'Esqueci minha senha']);
if (isset($message)) {
    ?>
    <div class="alert alert-danger" role="alert">
        <?= $message ?>
    </div>
    <?php
}
?>


<div class="col-md-12">
    <h1>Recuperar senha</h1>
    <h2>Informe seu e-mail</h2>
    <form class="" method="post" action="<?= $this->url(array('esqueci-senha')) ?>">
        <div class="form-group">
            <label for="email" class="cols-sm-2 control-label">Email</label>
            <input type="text" class="form-control" name="email" id="email" placeholder="Seu e-mail"/>
        </div>

        <div class="form-group ">
            <button type="submit" class="col-md-5 pull-left btn btn-danger btn-lg login-button">
                Recuperar senha
            </button>
        </div>
    </form>
</div>
