<?php
$this->layout('layout::main_template', ['title' => 'Homepage']);
?>

<div class="col-md-6">
    <h1>Sistema de Egressos</h1>
    <h2>Cadastro de novos Egressos</h2>
    <p>
        Acesse o link e preencha o formulário para realizar o seu cadastro para acessar informações exclusivas
    </p>
    <a href="/cadastrar" class="btn btn-default">
        Efetuar Cadastro
    </a>
</div>
<div class="col-md-6">
    <?= $this->insert('partials::login')?>
</div>
