<?php
/**
 * Created by PhpStorm.
 * User: ricardo
 * Date: 08/12/16
 * Time: 11:13
 */
$this->layout('layout::main_template', ['title' => 'Login']);
if (isset($message)) {
    ?>
    <div class="alert alert-danger" role="alert">
        <?= $message ?>
    </div>
    <?php
}
?>


<div class="col-md-12">
    <h1>Login</h1>
    <h2>Se já é cadastrado acesse sua área de egresso</h2>
    <form class="" method="post" action="<?= $this->url(array('login')) ?>">
        <div class="form-group">
            <label for="email" class="cols-sm-2 control-label">Email</label>
            <input type="text" class="form-control" name="email" id="email" placeholder="Seu e-mail"/>
        </div>

        <div class="form-group">
            <label for="password" class="cols-sm-2 control-label">Senha</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="Sua senha"/>
        </div>

        <div class="form-group ">
            <button type="submit" class="col-md-5 pull-left btn btn-danger btn-lg login-button">Esqueci minha senha
            </button>
            <button type="submit" class="col-md-5 pull-right btn btn-primary btn-lg login-button">Acessar o sistema
            </button>
        </div>
    </form>
</div>
