<?php
$this->layout('layout::main_template', ['title' => 'Oportunidades']);
?>
<div class=row>
    <div class="col-sm-12">
        <h1>Sistema de Egressos</h1>
    </div>
    <div class="col-md-4 sidebar-user">
        <?php $this->insert('partials::sidebar-user', ['usuario' => $usuario]) ?>
    </div>
    <div class="col-md-8">
        <h1>Oportunidades</h1>
        <div class="row">
            <h2 class="col-md-8">Exibindo vagas para : <?= $campus->nome ?></h2>
            <div class="col-md-4">
				<!--
			   <select name="campus" class="form-control" id="select-oportunidades">
                    <option>Selecione uma opção</option>
                    <?php
                   // foreach ($listaCampus as $item) {
                        ?>
                        <option value="oportunidades/< ?= $item->id ?>">< ?= $item->nome ?></option>
                        <?php
                   // }
                    ?>
                </select>
				-->
            </div>
        </div>
        <?php
        foreach ($oportunidades as $oportunidade) {
            ?>
            <div class="row">
                <div class="col-md-3">
                    <img class="img-responsive" src="<?= $oportunidade->imagem->caminho1 ?>" alt="">
                </div>
                <div class="col-md-9">
                    <h3><?= $oportunidade->nome ?></h3>
                    <hr>
                    <p><?= $oportunidade->descricao ?></p>
                    <p>Contato : <?= $oportunidade->contato ?></p>
                </div>
            </div>
            <hr>
            <?php
        }
        ?>
    </div>
</div>
